
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.HeadlessException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tapiwa
 */
public class NewJFrame extends javax.swing.JFrame {
private String imagePath;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EmailValue = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JTextField();
        PhoneNumberLabel = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FIRST NAME");

        jLabel2.setText("LAST NAME");

        jLabel3.setText("AGE");

        jLabel4.setText("PHONE NUMBER");

        EmailValue.setText("EMAIL ADDRESS");

        FirstNameLabel.setText("                         ");
        FirstNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameLabelActionPerformed(evt);
            }
        });

        LastNameLabel.setText("                                     ");
        LastNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameLabelActionPerformed(evt);
            }
        });

        PhoneNumberLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberLabelActionPerformed(evt);
            }
        });

        EmailLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailLabelActionPerformed(evt);
            }
        });

        jLabel6.setText("USER PROFILE");

        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("PHOTOGRAPH");

        UploadButton.setText("UPLOAD");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailValue)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberLabel)
                            .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameLabel)
                            .addComponent(AgeLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UploadButton)
                                            .addComponent(jButton2)))
                                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6)))
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailValue)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UploadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameLabelActionPerformed

    private void FirstNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameLabelActionPerformed

    private void PhoneNumberLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberLabelActionPerformed

    private void EmailLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailLabelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

Scanner scanner = new Scanner (System.in);
String firstnameValue = FirstNameLabel.getText();
String lastnameValue=LastNameLabel.getText();
String phonenumberValue=PhoneNumberLabel.getText();
String emailValue = EmailValue.getText();
String ageValue=AgeLabel.getText();

  ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(image);
        


 if (firstnameValue == null || firstnameValue.isEmpty() || lastnameValue == null || lastnameValue.isEmpty() || ageValue == null || ageValue.isEmpty() || emailValue == null || emailValue.isEmpty() || phonenumberValue == null || phonenumberValue.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please make sure you entered all the values!", "Form Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int age = 0;
        int phone = 0;
        String emailRegex = "^(.+)@(.+)$";

        boolean ageValidated = true;
        boolean phoneValidated = true;
        boolean emailValidated = true;

        try {
            age = Integer.parseInt(ageValue);
        } catch (NumberFormatException e) {
            ageValidated = false;
        }

        try {
            phone = Integer.parseInt(phonenumberValue);
        } catch (NumberFormatException e) {
            phoneValidated = false;
        }

        if (!emailValue.matches(emailRegex)) {
            emailValidated = false;
        }

        if (!ageValidated && !phoneValidated) {
            JOptionPane.showMessageDialog(this, "Only numbers allowed for age and phone number!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else if (!ageValidated) {
            JOptionPane.showMessageDialog(this, "Age must be in Numbers!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else if (!emailValidated) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else if (!phoneValidated) {
            JOptionPane.showMessageDialog(this, "Only numbers allowed for phone number!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } else if(imagePath == null || imagePath.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please verify you uploaded an image!", "Image Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "First name: " + firstnameValue + "\n" + "Last name: " + lastnameValue + "\n" + "Age " + ageValue + "\n" + "Email: " + emailValue + "\n" + "Phone Number: " + phonenumberValue + "\n", "User information", JOptionPane.PLAIN_MESSAGE, scaledIcon);
        }


JOptionPane.showMessageDialog(this, "First name: " + firstnameValue + "\n" + "Last name: " + lastnameValue + "\n" + "Age " + ageValue + "\n" + "Email: " + emailValue + "\n" + "Phone Number: " + phonenumberValue + "\n", "User information", JOptionPane.PLAIN_MESSAGE, scaledIcon);

System.out.println();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);

File image = chooser.getSelectedFile();
String filename = image.getAbsolutePath();
UploadButton.setText(filename);
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeLabel;
    private javax.swing.JTextField EmailLabel;
    private javax.swing.JLabel EmailValue;
    private javax.swing.JTextField FirstNameLabel;
    private javax.swing.JTextField LastNameLabel;
    private javax.swing.JTextField PhoneNumberLabel;
    private javax.swing.JButton UploadButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
